### ISSUE TITLE
Update to work with Next 12

### ISSUE THREAD

**Issue by benjaminsehl** [bundlesandbatches/next-sanity-image#23]

**Comment by matthewharwood** [comment]
So this doesn't work with next 12?

**Comment by lorenzodejong** [comment]
It seems like next/image is throwing a warning because the `width` query parameter is not implemented in the returned URL for the image. This has to do with @sanity/image-url mapping the `width` parameter to be the shorthand `w`: https://github.com/sanity-io/image-url/blob/main/src/urlForImage.ts#L14. I'll see what i can do about this.

Apart from this the library seems to work fine with Next.js 12, or did you guys encounter any other issue while upgrading?

**Comment by lorenzodejong** [comment]
I've just released version 3.1.8 which solves this warning and includes the PR from @elmarburke which adds Next.js ^ 12.0.0 as a peer dependency. If there are any additional problems feel free to open another issue.
