### ISSUE TITLE
Next 13 support

### ISSUE THREAD

**Issue by dRect911** [bundlesandbatches/next-sanity-image#46]
If it's possible may we have a support for next 13?

**Comment by jimCresswell** [comment]
I've opened a naive PR, but given some people already appear to be using this library with Next 13 I believe it's an overall improvement.

**Comment by lorenzodejong** [comment]
I haven't had time to test the implementation against Next 13 yet, is the library fully compatible with the newly introduced API in Next 13?

**Comment by jimCresswell** [comment]
I don't know yet, I'm in the process of updating a large Typescript application to Next 13 and React 18. Once the types are sorted out, I should be able to test application behaviour. We don't use all the next-sanity-image features so it wouldn't be an exhaustive test.

**Comment by jimCresswell** [comment]
Our update to Next 13 is proving challenging. We'll test once we can, but you might be in a position to verify sooner.

**Comment by lorenzodejong** [comment]
I've tested the library using Next 13, it seems to be correctly compatible. I've integrated the PR from @jimCresswell and updated the documentation. Version 5.0.0 has just been released.

The reason for a major update is caused by the dropped support for blur up options. Check out the upgrade guide for more information https://github.com/bundlesandbatches/next-sanity-image#upgrading-from-4xx-to-5xx.

If there are any issues with the upgrade, feel free to re-open or create a new issue!

**Comment by jimCresswell** [comment]
@lorenzodejong thank you so much! That is very helpful!

cc @mantagen
